name: 'Validate Blueprint'
description: 'Validate a blueprint change'
inputs:
  colony_token:  # id of input
    description: 'token for colony login'
    required: true
    default: ''
  colony_account:  # id of input
    description: 'Colony account to use'
    required: true
    default: ''
  colony_space:  # id of input
    description: 'Colony space to use'
    required: true
    default: ''
outputs:
  result: # output will be available to future steps 
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
